# Description:
#   Test data (Tensorflow checkpoints) for vp/pretrained tests.

licenses(["notice"])  # Apache 2.0 License

exports_files(["LICENSE"])

package(
    default_visibility = ["//sonnet/python:__pkg__"],
)

filegroup(
    name = "restore_initializer_test_checkpoint",
    srcs = glob(["restore_initializer_test_checkpoint.*"]),
)
