# Description:
#   Sonnet: DeepMind abstractions for Neural Networks in TensorFlow.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0 License

exports_files(["LICENSE"])

py_library(
    name = "sonnet",
    srcs = [
        "__init__.py",
    ],
    srcs_version = "PY2AND3",
    visibility = ["//visibility:public"],
    deps = [
        "//sonnet/python:modules",
        "//sonnet/python:ops",
        # tensorflow dep,
    ],
)
